name: build-windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install:
          make
          mingw-w64-x86_64-cc
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-libjpeg-turbo
    - name: make
      run: make
    - name: make debug
      run: make debug
    - name: make test
      run: make test
